name: Compile, test, deploy
on: ["push"]
env:
  GIPHY_API_KEY: ${{ secrets.giphy_api_key }}
jobs:
  steps1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout own repo
      uses: actions/checkout@v3
    - name: Setup Java 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.3
      with:
        maven-version: '3.8.4'
    - name: Run test
      run: mvn clean verify
    - name: Upload coverage badge to DigitalOcean spaces
      uses: BetaHuhn/do-spaces-action@v2
      with:
        access_key: ${{ secrets.access_key }}
        secret_key: ${{ secrets.secret_key }}
        space_name: aer
        space_region: sgp1
        source: .github/badges/jacoco.svg
        out_dir: coverage/${{ github.event.repository.name }}
        permission: public-read
    - name: Upload jacoco coverage report to DigitalOcean spaces
      uses: BetaHuhn/do-spaces-action@v2
      with:
        access_key: ${{ secrets.access_key }}
        secret_key: ${{ secrets.secret_key }}
        space_name: aer
        space_region: sgp1
        source: target/site/jacoco
        out_dir: coverage/${{ github.event.repository.name }}
        


   